services:
  predict_main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stocksense_main
    command: python3 -m app.main
    ports:
      - "5005:5005"
    volumes:
      - .:/app
      - ./app/db:/app/db
      - ./app/templates:/app/templates
      - ./model/saved_models:/app/model/saved_models
      - pip_cache:/root/.cache/pip
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - FLASK_PORT=5005
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "python3", "-c", "import requests; requests.get('http://localhost:5005/health', timeout=5)" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  model_monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stocksense_monitor
    command: python3 -m scripts.model_monitor_scheduler
    volumes:
      - .:/app
      - ./app/db:/app/db
      - ./model/saved_models:/app/model/saved_models
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - TZ=Asia/Kolkata
    depends_on:
      predict_main:
        condition: service_started
    restart: unless-stopped

volumes:
  pip_cache:
